# Generated by Django 5.1.5 on 2025-01-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to='uploads/files/'),
        ),
    ]
